### ISSUE TITLE
More gateways

### ISSUE THREAD

**Issue by cmMcKeevek** [ahwm/payment-gateway-client#1]
This one too
https://0merchant.transactiongateway.com/gw/merchants/resources/integration/integration_portal.php
And this one, I think
https://www.durangomerchantservices.com/wp-content/uploads/2014/12/Durango-Gateway-Three-Step-Redirect-API.pdf

**Comment by cmMcKeevek** [comment]
https://secure.easypaydirectgateway.com/gw/merchants/resources/integration/integration_portal.php

**Comment by cmMcKeevek** [comment]
https://secure.merchantonegateway.com/merchants/resources/integration/integration_portal.php

**Comment by ahwm** [comment]
Nice finds! I'll review them and get them added. Thanks!

**Comment by ahwm** [comment]
It looks like the durangomerchantservices one is: https://durangomerchantservices.com/gateway-integration-instructions/

https://secure.durango-direct.com/merchants/resources/integration/integration_portal.php#methodology
